### ISSUE TITLE
Surface preferences by flocs for deposition?

### ISSUE THREAD

**Issue by JacquelineDokko** [AguaClara/filter-constrictions#10]
Do flocs/PACl prefer to deposit on rough sand particle surfaces or other flocs which might have some exposed PACl surface? Consider electrostatic interactions and physical interactions.

Posted 2/27/18

**Comment by lucindali** [comment]
This isn't something we have looked at on the StaRS theory team, so I'm not sure. It seems like rough surfaces make for much better surfaces to deposit onto, but I am not sure about the relative likelihood for particle to deposit on a rough surface compared to the stickiness of PACl. Some things to consider might be the electrostatic forces between PACl and a less charged sand (I believe) vs the more negatively charged clay.

**Comment by lucindali** [comment]
But there will be a greater affinity for physical deposition mechanisms for a rough sand grain.
