### ISSUE TITLE
Issue with the LED

### ISSUE THREAD

**Issue by JonathanDavidHarris** [AguaClara/filter-constrictions#14]
The LED is not working when the team plugs it in. After a bit of testing, we realized it is because the white wire is no longer soldered on.

**Comment by JonathanDavidHarris** [comment]
@MattCimini My team needs to learn how to use the solder. Would you be able to help us one day this week?

**Comment by JacquelineDokko** [comment]
Fixed the LED with the help of Matt's soldering lesson
