### ISSUE TITLE
Capture video of flocs in the constriction

### ISSUE THREAD

**Issue by JonathanDavidHarris** [AguaClara/filter-constrictions#8]
Upon testing the different constrictions and turbidities, we hope to capture the change in flow behavior with time. 
By April 19th, 2018

**Comment by JacquelineDokko** [comment]
Initial video of 2D model has been recorded and saved onto AguaClara shared folder under sp18 within Filter Constrictions research. May have to adjust recording fps (?) to increase quality of videos for analysis in the future. If FPS is not the issue, then figure out what can be changed to address this all while being able to record and save large video files.

**Comment by JonathanDavidHarris** [comment]
The team is unable to save the videos directly to Github since the files are said to be too large. Therefore the videos for the Spring 2018 Filter Constriction Team are saved [here](https://drive.google.com/drive/u/0/folders/1KcERCS7CeTcpNgrQGueZKAfhjzMBFqGU). Folder names correspond to the dates the videos were taken.
